### ISSUE TITLE
Plugin download is broken since bws-1.0.0 was released

### ISSUE THREAD

**Issue by returntrip** [asdf-community/asdf-bitwarden-secrets-manager#8]
**Describe the bug**

Since bws-1.0.0 was released 3 days ago, `asdf` is unable to download that version of the plugin because `get_release_name` function [here](https://github.com/asdf-community/asdf-bitwarden-secrets-manager/blob/52360276a405714d6679e1ff75006e4f6082e5b9/lib/utils.bash#L55) is finding 2 tags for version 1.0.0. I.e.:

```
bitwarden-v1.0.0
bws-v1.0.0
```

**Steps to reproduce**
```
asdf install bitwarden-secrets-manager 1.0.0
* Downloading bitwarden-secrets-manager release 1.0.0...
curl: (3) URL rejected: Malformed input to a URL function
asdf-bitwarden-secrets-manager: Could not download https://github.com/bitwarden/sdk/releases/download/bitwarden-v1.0.0
bws-v1.0.0/bws-x86_64-unknown-linux-gnu-1.0.0.zip
```
**Expected behavior**

bws 1.0.0 is installed successfully

**Additional context**

Perhaps this could be fixed by adjusting the funciton like so:

```
get_release_name() {
	local -r version=$1

	git ls-remote --tags --refs "$GH_REPO" |
		grep -o 'refs/tags/.*' | cut -d/ -f3- |
		grep "^bws-v$version"
}

**Comment by xitij2000** [comment]
This should be fixed by: https://github.com/asdf-community/asdf-bitwarden-secrets-manager/pull/9

**Comment by FIAV1** [comment]
Yes, thanks @xitij2000 😃
